# Generated by Django 3.2.2 on 2021-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210514_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.CharField(max_length=65535),
        ),
    ]
